---
# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-ast
      - id: debug-statements
      - id: mixed-line-ending

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ['--profile', 'black']

  # Linting and formatting with Ruff (fast Python linter & formatter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format  # Add Ruff formatter

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-python-dateutil
          - types-requests
          - pydantic
        args: ['--config-file=pyproject.toml']  # Use pyproject.toml settings
        files: ^productivity_tracker/  # Only check the main package
        exclude: ^productivity_tracker/migrations/

  # Security checks with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']
