"""add_versioning_feature_flags

Revision ID: 6f38e96a8381
Revises: 581d7b5f64a2
Create Date: 2025-11-09 11:49:49.384003

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f38e96a8381'
down_revision: Union[str, Sequence[str], None] = '581d7b5f64a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False, comment="Semantic version string (e.g., '0.1.0-beta')"),
    sa.Column('major', sa.Integer(), nullable=False, comment='Major version number'),
    sa.Column('minor', sa.Integer(), nullable=False, comment='Minor version number'),
    sa.Column('patch', sa.Integer(), nullable=False, comment='Patch version number'),
    sa.Column('prerelease', sa.String(length=50), nullable=True, comment="Prerelease identifier (e.g., 'beta', 'rc.1')"),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Human-readable version name'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Lifecycle status (planned, active, deprecated, etc.)'),
    sa.Column('api_prefix', sa.String(length=50), nullable=False, comment="API route prefix (e.g., '/api/v0.1')"),
    sa.Column('release_date', sa.Date(), nullable=True, comment='Official release date'),
    sa.Column('eol_date', sa.Date(), nullable=True, comment='End-of-life date'),
    sa.Column('breaking', sa.Boolean(), nullable=False, comment='Whether this version has breaking changes'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Release notes or additional information'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major', 'minor', 'patch', 'prerelease', name='uq_version_components')
    )
    op.create_index(op.f('ix_versions_status'), 'versions', ['status'], unique=False)
    op.create_index(op.f('ix_versions_version'), 'versions', ['version'], unique=True)
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False, comment="Feature enum key (e.g., 'TIME_TRACKING')"),
    sa.Column('feature_name', sa.String(length=200), nullable=False, comment='Human-readable feature name'),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether the feature is enabled'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Feature category (foundation, security, productivity, etc.)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Feature description'),
    sa.Column('override_dev', sa.Boolean(), nullable=True, comment='Override for development environment'),
    sa.Column('override_staging', sa.Boolean(), nullable=True, comment='Override for staging environment'),
    sa.Column('override_prod', sa.Boolean(), nullable=True, comment='Override for production environment'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'feature_key', name='uq_version_feature')
    )
    op.create_index(op.f('ix_feature_flags_feature_key'), 'feature_flags', ['feature_key'], unique=False)
    op.create_index(op.f('ix_feature_flags_version_id'), 'feature_flags', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_flags_version_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_feature_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_versions_version'), table_name='versions')
    op.drop_index(op.f('ix_versions_status'), table_name='versions')
    op.drop_table('versions')
    # ### end Alembic commands ###
